# Generated by Django 3.1.4 on 2020-12-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_done', models.BooleanField()),
                ('created_date', models.DateTimeField(verbose_name='Date create')),
            ],
        ),
    ]
